# Use the official Nginx image
FROM nginx:latest

# Copy your custom Nginx configuration file to the container
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 80 (HTTP) for web traffic
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
