# Use an official PHP-FPM image as the parent image
FROM php:8.0-fpm

# Install any necessary PHP extensions and dependencies
RUN apt-get update && \
    apt-get install -y libpq-dev && \
    docker-php-ext-install pdo pdo_pgsql

# Set the working directory in the container
WORKDIR /var/backend/
# Copy the rest of the data
COPY /app/backend/ ./
# Expose the port on which PHP-FPM will listen (typically 9000)
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]
